In [18]:
import pandas as pd

df = pd.read_csv('/Users/JooAnLee/final_project/db/news_2023_2025_with_NER.csv')
df.head()

,news_id,wdate,title,article,press,url,image,text_combined,labels_by_id
0,20250523_0001,2025-05-23 19:11,[마켓인]모태펀드 존속 불확실성 해소될까…이재명 공약에 업계 주목,"2035년 종료 앞둬, 존속 공약에 기대감\n창업 초기자금 공백 완화 가능성에 업계...",이데일리,https://n.news.naver.com/mnews/article/018/000...,https://imgnews.pstatic.net/image/018/2025/05/...,[마켓인]모태펀드 존속 불확실성 해소될까…이재명 공약에 업계 주목 2035년 종료 ...,[]
1,20250523_0002,2025-05-23 18:52,"[단독] 카카오페이, 2500만 회원 쓱·스마일페이 품나…간편결제 시장 빅3 경쟁 후끈",매각가 5000억 안팎 달할듯\n결제시장 내 입지강화 포석\n카카오페이 [사진 = ...,매일경제,https://n.news.naver.com/mnews/article/009/000...,https://imgnews.pstatic.net/image/009/2025/05/...,"[단독] 카카오페이, 2500만 회원 쓱·스마일페이 품나…간편결제 시장 빅3 경쟁 ...",['카카오페이']
2,20250523_0003,2025-05-23 18:38,"키스트론, 일반 청약 흥행…증거금 6조원 모았다","5월22~23일 청약 진행, 경쟁률 총2166대1\n상장 후 예상 시가총개 643억...",머니투데이,https://n.news.naver.com/mnews/article/008/000...,https://imgnews.pstatic.net/image/008/2025/05/...,"키스트론, 일반 청약 흥행…증거금 6조원 모았다 5월22~23일 청약 진행, 경쟁률...",[]
3,20250523_0004,2025-05-23 18:33,"골드만삭스 차기 CEO, 이재용·김병주·이창용 만났다",[사진=연합뉴스]\n세계 2위 투자은행(IB)인 골드만삭스의 사장 겸 최고운영책임자...,매일경제,https://n.news.naver.com/mnews/article/009/000...,https://imgnews.pstatic.net/image/009/2025/05/...,"골드만삭스 차기 CEO, 이재용·김병주·이창용 만났다 [사진=연합뉴스] 세계 2위 ...",['삼성전자']
4,20250523_0005,2025-05-23 18:24,흔들리는 미국…달러 패권 붕괴에 '스테이블코인' 선택한 美,/사진=게티이미지뱅크\n미국 정부가 달러의 기축통화 지위를 위협하는 금에 대응하기 ...,머니투데이,https://n.news.naver.com/mnews/article/008/000...,https://imgnews.pstatic.net/image/008/2025/05/...,흔들리는 미국…달러 패권 붕괴에 '스테이블코인' 선택한 美 /사진=게티이미지뱅크 미...,['상상인증권']

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58405 entries, 0 to 58404
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   news_id        58405 non-null  object
 1   wdate          58405 non-null  object
 2   title          58405 non-null  object
 3   article        58405 non-null  object
 4   press          58405 non-null  object
 5   url            58405 non-null  object
 6   image          58405 non-null  object
 7   text_combined  58405 non-null  object
 8   labels_by_id   58405 non-null  object
dtypes: object(9)
memory usage: 4.0+ MB

# 외부요인 수집
1. 거시 경제 지표
- 금리
- 미국-한국 금리차
- 국고채 10년물 수익률
- 환율
2. 기업 내부 실적 관련
- 매출
- 당기순이익, 순자산 (PER, PBR)|
- 산업별 생산 지수
3. 매매 동향 (기술적 지표)
- D+1, D+2, D+3, D+7, D+14, D+21, D+30, 뉴스발행일 30일 전후 가격 등락율(impact_score)
- 주가 등락율
- 외국인 순매수
- 기관 순매수
- 개인 순매수
- 거래량

## PyKRX

In [20]:
pip install pykrx

Requirement already satisfied: pykrx in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (1.0.51)
Requirement already satisfied: requests in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.32.3)
Requirement already satisfied: pandas in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.2.3)
Requirement already satisfied: datetime in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (5.5)
Requirement already satisfied: numpy in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.0.2)
Requirement already satisfied: xlrd in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.0.1)
Requirement already satisfied: deprecated in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (1.2.18)
Requirement already satisfied: multipledispatch in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (1.0.0)
Requirement already satisfied: matplotlib in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (3.9.4)
Requirement already satisfied: zope.interface in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from datetime->pykrx) (7.2)
Requirement already satisfied: pytz in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from datetime->pykrx) (2025.2)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from deprecated->pykrx) (1.17.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib->pykrx) (3.22.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->pykrx) (1.17.0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pandas->pykrx) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (2025.4.26)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from zope.interface->datetime->pykrx) (78.1.1)
Note: you may need to restart the kernel to use updated packages.

In [41]:
pip install --upgrade pykrx

Requirement already satisfied: pykrx in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (1.0.51)
Requirement already satisfied: requests in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.32.3)
Requirement already satisfied: pandas in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.2.3)
Requirement already satisfied: datetime in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (5.5)
Requirement already satisfied: numpy in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.0.2)
Requirement already satisfied: xlrd in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (2.0.1)
Requirement already satisfied: deprecated in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (1.2.18)
Requirement already satisfied: multipledispatch in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (1.0.0)
Requirement already satisfied: matplotlib in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pykrx) (3.9.4)
Requirement already satisfied: zope.interface in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from datetime->pykrx) (7.2)
Requirement already satisfied: pytz in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from datetime->pykrx) (2025.2)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from deprecated->pykrx) (1.17.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from matplotlib->pykrx) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib->pykrx) (3.22.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->pykrx) (1.17.0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from pandas->pykrx) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from requests->pykrx) (2025.4.26)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/final_jn/lib/python3.9/site-packages (from zope.interface->datetime->pykrx) (78.1.1)
Note: you may need to restart the kernel to use updated packages.

In [42]:
from pykrx import stock
from pykrx import bond
import datetime

In [22]:
import pandas as pd
import ast

def extract_last_company_name(labels):
    # NaN 또는 빈 값 처리
    if pd.isna(labels) or labels == '[]' or labels == '':
        return None
    # 문자열인 경우 리스트로 변환
    if isinstance(labels, str):
        try:
            labels_list = ast.literal_eval(labels)
        except Exception:
            return None
    elif isinstance(labels, list):
        labels_list = labels
    else:
        return None
    # 빈 리스트 처리
    if not labels_list:
        return None
    # 마지막 값 반환
    return labels_list[-1]

# 적용
df['stock_name'] = df['labels_by_id'].apply(extract_last_company_name)

In [23]:
df.tail()

,news_id,wdate,title,article,press,url,image,text_combined,labels_by_id,stock_name
58400,20240101_0045,2024-01-01 07:02,매일 2억 버는데 시총 2500억?…더네이쳐홀딩스 본사 가보니 [윤현주의 主食이 주식],‘패션 강자’ 더네이쳐홀딩스 본사를 가다\n박영준 대표 1년여 만에 언론 인터뷰\n...,한국경제,https://n.news.naver.com/mnews/article/015/000...,https://imgnews.pstatic.net/image/015/2024/01/...,매일 2억 버는데 시총 2500억?…더네이쳐홀딩스 본사 가보니 [윤현주의 主食이 주...,['NH투자증권'],NH투자증권
58401,20240101_0046,2024-01-01 07:02,"부자 돈 굴리는 강남 '꾼'들의 선택…""올해 '이 종목' 뜬다"" [신민경의 테마록]","6개 증권사 '강남권 PB'들에게 물었더니…\n""강한 테마만 살아남는다""\nAI 반...",한국경제,https://n.news.naver.com/mnews/article/015/000...,https://imgnews.pstatic.net/image/015/2024/01/...,"부자 돈 굴리는 강남 '꾼'들의 선택…""올해 '이 종목' 뜬다"" [신민경의 테마록]...","['CJ대한통운', '유안타증권', '한국콜마', '엔씨소프트', '두산에너빌리티'...",SK하이닉스
58402,20240101_0049,2024-01-01 06:03,태영건설 파장 속 PF-ABCP '거래 부진'…차환 우려 고개,"PF 구조조정에 건설업 기피심리↑…""익숙한 악재라 파장 적을 것"" 관측도\n워크아웃...",연합뉴스,https://n.news.naver.com/mnews/article/001/001...,https://imgnews.pstatic.net/image/001/2024/01/...,태영건설 파장 속 PF-ABCP '거래 부진'…차환 우려 고개 PF 구조조정에 건설...,"['삼성증권', '태영건설']",태영건설
58403,20240101_0051,2024-01-01 06:00,"신세계 센텀시티, 지방 백화점 최초로 연 매출 2조원 달성",신세계 센텀시티\n[신세계백화점 제공. 재판매 및 DB 금지]\n(서울=연합뉴스) ...,연합뉴스,https://n.news.naver.com/mnews/article/001/001...,https://imgnews.pstatic.net/image/001/2024/01/...,"신세계 센텀시티, 지방 백화점 최초로 연 매출 2조원 달성 신세계 센텀시티 [신세계...",['신세계'],신세계
58404,20240101_0053,2024-01-01 05:01,금리인하 본격화되는 2024년... 글로벌 증시 전망은 '맑음',"*재판매 및 DB 금지 /사진=뉴시스\n[파이낸셜뉴스] 지난해 미국, 일본 등 글로...",파이낸셜뉴스,https://n.news.naver.com/mnews/article/014/000...,https://imgnews.pstatic.net/image/014/2024/01/...,금리인하 본격화되는 2024년... 글로벌 증시 전망은 '맑음' *재판매 및 DB ...,['미래에셋증권'],미래에셋증권

In [45]:
from pykrx import stock

# 최근 영업일(예: 2024년 12월 31일)로 고정
recent_date = "2025-06-03"
kospi_tickers = stock.get_market_ticker_list(date=recent_date, market="KOSPI")
ticker_name_map = {stock.get_market_ticker_name(ticker): ticker for ticker in kospi_tickers}

In [46]:
def get_ticker_from_name(name):
    if pd.isna(name):
        return None
    return ticker_name_map.get(name)

df['ticker'] = df['stock_name'].apply(get_ticker_from_name)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58405 entries, 0 to 58404
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   news_id              58405 non-null  object
 1   wdate                58405 non-null  datetime64[ns]
 2   title                58405 non-null  object
 3   article              58405 non-null  object
 4   press                58405 non-null  object
 5   url                  58405 non-null  object
 6   image                58405 non-null  object
 7   text_combined        58405 non-null  object
 8   labels_by_id         58405 non-null  object
 9   stock_name           35238 non-null  object
 10  ticker               35132 non-null  object
 11  D_minus_30_date      58405 non-null  datetime64[ns]
 12  D_day_date           58405 non-null  datetime64[ns]
 13  D_plus_1_date        58405 non-null  datetime64[ns]
 14  D_plus_2_date        58405 non-null  datetime64[ns]
 15  D_plus_3_date        58405 non-null  datetime64[ns]
 16  D_plus_7_date        58405 non-null  datetime64[ns]
 17  D_plus_14_date       58405 non-null  datetime64[ns]
 18  D_plus_21_date       58405 non-null  datetime64[ns]
 19  D_plus_30_date       58405 non-null  datetime64[ns]
 20  D-30                 0 non-null      float64
 21  close_D-day          0 non-null      float64
 22  D+1                  0 non-null      float64
 23  D+2                  0 non-null      float64
 24  D+3                  0 non-null      float64
 25  D+7                  0 non-null      float64
 26  D+14                 0 non-null      float64
 27  D+21                 0 non-null      float64
 28  D+30                 0 non-null      float64
 29  D-day_volume         0 non-null      float64
 30  D-day_change         0 non-null      float64
 31  impact_score         0 non-null      float64
 32  foreign_trading      0 non-null      float64
 33  institution_trading  0 non-null      float64
 34  individual_trading   0 non-null      float64
dtypes: datetime64[ns](10), float64(15), object(10)
memory usage: 15.6+ MB

### Pykrx에서 데이터 수집
- D-30 : 뉴스발행일 기준 30일전 종가
- close_D-day : 뉴스발행일 종가
- D+1 : 뉴스발행일 하루 후 종가
- D+2 : 뉴스발행일 이틀 뒤 종가
- D+3 : 뉴스발행일 3일뒤 종가
- D+7 : 뉴스발행일 일주일 뒤 종가
- D+14 : 뉴스발행일 2주 뒤 종가
- D+21 : 뉴스발행일 3주 뒤 종가
- D+30 : 뉴스발행일 한달 뒤 종가
- impact_score : {(D+30) - (D-30)}/(D-30) * 100 (뉴스발행일 한달 뒤 종가와 뉴스발행일 30일전 종가 등락률)
- D-day_volume : 뉴스발행일 거래량
- D-day_change : 뉴스발행일 등락률
- foreign_trading : 뉴스발행일 기준 외인 순매수량
- institution_trading : 뉴스발행일 기준 기관 순매수량
- individual_trading : 뉴스발행일 기준 개인 순매수량

In [48]:
import pandas as pd
from datetime import timedelta

df['wdate'] = pd.to_datetime(df['wdate'])

# 필요한 날짜 계산
df['D_minus_30_date'] = df['wdate'] - timedelta(days=30)
df['D_day_date'] = df['wdate']
df['D_plus_1_date'] = df['wdate'] + timedelta(days=1)
df['D_plus_2_date'] = df['wdate'] + timedelta(days=2)
df['D_plus_3_date'] = df['wdate'] + timedelta(days=3)
df['D_plus_7_date'] = df['wdate'] + timedelta(days=7)
df['D_plus_14_date'] = df['wdate'] + timedelta(days=14)
df['D_plus_21_date'] = df['wdate'] + timedelta(days=21)
df['D_plus_30_date'] = df['wdate'] + timedelta(days=30)

In [49]:
date_cols = [
    'D_minus_30_date', 'D_day_date', 'D_plus_1_date', 'D_plus_2_date',
    'D_plus_3_date', 'D_plus_7_date', 'D_plus_14_date', 'D_plus_21_date', 'D_plus_30_date'
]
all_dates = set()
for col in date_cols:
    all_dates.update(df[col].dt.strftime('%Y%m%d').tolist())
all_dates = sorted(list(all_dates))
all_tickers = df['ticker'].dropna().unique().tolist()

In [50]:
from pykrx import stock
import numpy as np

ohlcv_dict = {}
for ticker in all_tickers:
    try:
        ohlcv = stock.get_market_ohlcv_by_date(
            fromdate=min(all_dates),
            todate=max(all_dates),
            ticker=ticker
        )
        ohlcv_dict[ticker] = ohlcv
    except:
        continue

In [51]:
def get_ohlcv_val(ticker, date, col):
    if pd.isna(ticker) or pd.isna(date):
        return np.nan
    date_str = date.strftime('%Y%m%d')
    if ticker not in ohlcv_dict:
        return np.nan
    df_ticker = ohlcv_dict[ticker]
    if date_str not in df_ticker.index:
        return np.nan
    return df_ticker.loc[date_str, col]

In [52]:
# 종가
df['D-30'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_minus_30_date'], '종가'), axis=1)
df['close_D-day'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_day_date'], '종가'), axis=1)
df['D+1'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_1_date'], '종가'), axis=1)
df['D+2'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_2_date'], '종가'), axis=1)
df['D+3'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_3_date'], '종가'), axis=1)
df['D+7'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_7_date'], '종가'), axis=1)
df['D+14'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_14_date'], '종가'), axis=1)
df['D+21'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_21_date'], '종가'), axis=1)
df['D+30'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_plus_30_date'], '종가'), axis=1)

# 거래량, 등락률 (뉴스 발행일 기준)
df['D-day_volume'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_day_date'], '거래량'), axis=1)
df['D-day_change'] = df.apply(lambda row: get_ohlcv_val(row['ticker'], row['D_day_date'], '등락률'), axis=1)

외국인/기관/개인 순매수

In [54]:
from pykrx import stock

# 필요한 날짜 범위
date_min = df['D_day_date'].min().strftime('%Y%m%d')
date_max = df['D_day_date'].max().strftime('%Y%m%d')
all_tickers = df['ticker'].dropna().unique().tolist()

# 종목별 데이터 캐싱
trading_dict = {}
for ticker in all_tickers:
    try:
        tv_df = stock.get_market_trading_value_by_date(date_min, date_max, ticker)
        trading_dict[ticker] = tv_df
    except:
        continue

In [56]:
def fast_trading_value(ticker, date, investor):
    if pd.isna(ticker) or pd.isna(date):
        return np.nan
    date_str = date.strftime('%Y%m%d')
    if ticker not in trading_dict:
        return np.nan
    tv_df = trading_dict[ticker]
    if date_str not in tv_df.index:
        return np.nan
    col_map = {
        '외국인': '외국인합계',
        '기관': '기관합계',
        '개인': '개인'
    }
    return tv_df.loc[date_str, col_map[investor]]

df['foreign_trading'] = df.apply(lambda row: fast_trading_value(row['ticker'], row['D_day_date'], '외국인'), axis=1)
df['institution_trading'] = df.apply(lambda row: fast_trading_value(row['ticker'], row['D_day_date'], '기관'), axis=1)
df['individual_trading'] = df.apply(lambda row: fast_trading_value(row['ticker'], row['D_day_date'], '개인'), axis=1)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58405 entries, 0 to 58404
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   news_id              58405 non-null  object
 1   wdate                58405 non-null  datetime64[ns]
 2   title                58405 non-null  object
 3   article              58405 non-null  object
 4   press                58405 non-null  object
 5   url                  58405 non-null  object
 6   image                58405 non-null  object
 7   text_combined        58405 non-null  object
 8   labels_by_id         58405 non-null  object
 9   stock_name           35238 non-null  object
 10  ticker               35132 non-null  object
 11  D_minus_30_date      58405 non-null  datetime64[ns]
 12  D_day_date           58405 non-null  datetime64[ns]
 13  D_plus_1_date        58405 non-null  datetime64[ns]
 14  D_plus_2_date        58405 non-null  datetime64[ns]
 15  D_plus_3_date        58405 non-null  datetime64[ns]
 16  D_plus_7_date        58405 non-null  datetime64[ns]
 17  D_plus_14_date       58405 non-null  datetime64[ns]
 18  D_plus_21_date       58405 non-null  datetime64[ns]
 19  D_plus_30_date       58405 non-null  datetime64[ns]
 20  D-30                 19557 non-null  float64
 21  close_D-day          32449 non-null  float64
 22  D+1                  27035 non-null  float64
 23  D+2                  20987 non-null  float64
 24  D+3                  20244 non-null  float64
 25  D+7                  30561 non-null  float64
 26  D+14                 30474 non-null  float64
 27  D+21                 30024 non-null  float64
 28  D+30                 20013 non-null  float64
 29  D-day_volume         32449 non-null  float64
 30  D-day_change         32410 non-null  float64
 31  impact_score         7300 non-null   float64
 32  foreign_trading      32334 non-null  float64
 33  institution_trading  32334 non-null  float64
 34  individual_trading   32334 non-null  float64
dtypes: datetime64[ns](10), float64(15), object(10)
memory usage: 15.6+ MB

In [62]:
# stock_name은 있는데 ticker가 없는 행만 추출
missing_ticker_df = df[(df['stock_name'].notnull()) & (df['ticker'].isnull())]

# 예시 5개만 출력
print(missing_ticker_df[['stock_name', 'ticker']].head())

    stock_name ticker
140      달바글로벌   None
145      달바글로벌   None
200      달바글로벌   None
211      달바글로벌   None
223      달바글로벌   None

In [64]:
# close_D-day는 있는데 D-30은 없는 경우 추출
filtered_df = df[(df['close_D-day'].notnull()) & (df['D-30'].isnull())]

# stock_name과 ticker만 보기 (예시 10개)
print(filtered_df[['stock_name', 'ticker', 'close_D-day', 'D-30']].head(10))

    stock_name  ticker  close_D-day  D-30
467     한국금융지주  071050      96700.0   NaN
468      삼성SDI  006400     161500.0   NaN
470      NAVER  035420     185000.0   NaN
472     SK하이닉스  000660     202000.0   NaN
473       키움증권  039490     144400.0   NaN
474         KT  030200      51900.0   NaN
475       삼성전자  005930      55900.0   NaN
476     NH투자증권  005940      15840.0   NaN
480     LG생활건강  051900     312000.0   NaN
481       산일전기  062040      67100.0   NaN

In [65]:
# ticker는 있고 close_D-day가 없는 경우만 필터링
filtered_df = df[(df['ticker'].notnull()) & (df['close_D-day'].isnull())]

# 원하는 컬럼만 추출
result_df = filtered_df[['wdate', 'stock_name', 'ticker', 'close_D-day']]

# 예시 10개 출력
print(result_df.head(10))

                  wdate stock_name  ticker  close_D-day
829 2025-05-18 19:33:00   LG에너지솔루션  373220          NaN
830 2025-05-18 18:09:00       대한항공  003490          NaN
831 2025-05-18 18:05:00      SK텔레콤  017670          NaN
832 2025-05-18 18:05:00      롯데케미칼  011170          NaN
833 2025-05-18 18:02:00      상상인증권  001290          NaN
835 2025-05-18 18:02:00       대신증권  003540          NaN
836 2025-05-18 18:02:00   삼성바이오로직스  207940          NaN
837 2025-05-18 17:57:00       삼성증권  016360          NaN
838 2025-05-18 17:23:00       삼성증권  016360          NaN
839 2025-05-18 17:22:00     에이블씨엔씨  078520          NaN

In [68]:
# stock_name이 'SK텔레콤'인 행 중 하나 전체 보기
sk_telecom_row = df[df['stock_name'] == 'SK텔레콤'].head(1)
print(sk_telecom_row)

           news_id               wdate  \
640  20250520_0189 2025-05-20 06:41:00

                                      title  \
640  [증권신고서 읽는 기자]SKT 해킹에 주가 오르자 유증 나선 엑스큐어

                                               article  press  \
640  주가 3000원대에서 6000원대로 '급등'\n조달자금 140억원 USIM사업 투입...  아시아경제

                                                   url  \
640  https://n.news.naver.com/mnews/article/277/000...

                                                 image  \
640  https://imgnews.pstatic.net/image/277/2025/05/...

                                         text_combined labels_by_id  \
640  [증권신고서 읽는 기자]SKT 해킹에 주가 오르자 유증 나선 엑스큐어 주가 3000...    ['SK텔레콤']

    stock_name  ...      D+7 D+14 D+21 D+30 D-day_volume D-day_change  \
640      SK텔레콤  ...  51800.0  NaN  NaN  NaN     543658.0     0.585938

    impact_score foreign_trading institution_trading individual_trading
640          NaN   -7.481837e+09        1.744077e+09       5.570705e+09

[1 rows x 35 columns]

In [69]:
# D-day_volume 값은 있는데 D-day_change 값은 없는 경우 필터링
filtered_df2 = df[(df['D-day_volume'].notnull()) & (df['D-day_change'].isnull())]

# 원하는 컬럼만 추출
result2 = filtered_df2[['wdate', 'stock_name', 'ticker', 'close_D-day', 'D-day_volume', 'D-day_change']]

# 예시 10개 출력
print(result2.head(10))

                    wdate stock_name  ticker  close_D-day  D-day_volume  \
17875 2024-12-16 16:21:00     엠앤씨솔루션  484870      51800.0     3164985.0
17945 2024-12-16 09:38:00     엠앤씨솔루션  484870      51800.0     3164985.0
18014 2024-12-16 06:01:00     엠앤씨솔루션  484870      51800.0     3164985.0
22850 2024-11-06 16:20:00      더본코리아  475560      51400.0    18645439.0
22856 2024-11-06 16:07:00      더본코리아  475560      51400.0    18645439.0
22865 2024-11-06 15:16:00      더본코리아  475560      51400.0    18645439.0
22914 2024-11-06 10:57:00      더본코리아  475560      51400.0    18645439.0
22930 2024-11-06 09:41:00      더본코리아  475560      51400.0    18645439.0
22938 2024-11-06 09:24:00      더본코리아  475560      51400.0    18645439.0
22945 2024-11-06 09:11:00      더본코리아  475560      51400.0    18645439.0

       D-day_change
17875           NaN
17945           NaN
18014           NaN
22850           NaN
22856           NaN
22865           NaN
22914           NaN
22930           NaN
22938           NaN
22945           NaN

## 환율